In [66]:
class MeraLR:
    def __init__(self):
        self.m=0
        self.b=0
    def train(self,x_train,y_train):
        d=0
        n=0
        for i in range(x_train.shape[0]):
            n=n+(x_train[i]-x_train.mean())*(y_train[i]-y_train.mean())
            d=d+(x_train[i]-x_train.mean())**2
        self.m=n/d
        self.b = y_train.mean() - (self.m * x_train.mean())
        print(self.m)
        print(self.b) 
        
    def predict(self,x_test):
        print(x_test)
        return self.m*x_test+self.b
        

In [54]:
df=pd.read_csv("placement.csv")

In [41]:
import numpy as np
import pandas as pd


In [42]:
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_train ,y_train,test_size=0.2,random_state=2)

In [60]:
lr=MeraLR()
x_train=df.iloc[:,0:1].values
y_train=df.iloc[:,-1].values

In [61]:
lr.train(x_train,y_train)

[0.56959129]
[-0.98567795]


In [62]:
x_test

array([[8.58],
       [7.15],
       [5.88],
       [6.22],
       [4.57],
       [4.79],
       [5.32],
       [6.86],
       [8.35],
       [6.87],
       [8.94],
       [7.9 ],
       [6.93],
       [5.91],
       [7.32],
       [7.82],
       [5.09],
       [7.42],
       [6.94],
       [7.73],
       [6.19],
       [7.28],
       [6.73],
       [7.2 ],
       [8.21],
       [6.75],
       [7.87],
       [7.6 ],
       [8.63],
       [5.12],
       [8.15],
       [7.36],
       [8.31],
       [6.6 ],
       [6.59],
       [7.47],
       [7.93],
       [6.29],
       [6.37],
       [6.47]])

In [58]:
x_train

array([[6.89],
       [5.12],
       [7.82],
       [7.42],
       [6.94],
       [7.89],
       [6.73],
       [6.75],
       [6.09],
       [8.31],
       [5.32],
       [6.61],
       [8.94],
       [6.93],
       [7.73],
       [7.25],
       [6.84],
       [5.38],
       [6.94],
       [7.48],
       [7.28],
       [6.85],
       [6.14],
       [6.19],
       [6.53],
       [7.28],
       [8.31],
       [5.42],
       [5.94],
       [7.15],
       [7.36],
       [8.1 ],
       [6.96],
       [6.35],
       [7.34],
       [6.87],
       [5.99],
       [5.9 ],
       [8.62],
       [7.43],
       [9.38],
       [6.89],
       [5.95],
       [7.66],
       [5.09],
       [7.87],
       [6.07],
       [5.84],
       [8.63],
       [8.87],
       [9.58],
       [9.26],
       [8.37],
       [6.47],
       [6.86],
       [8.2 ],
       [5.84],
       [6.6 ],
       [6.92],
       [7.56],
       [5.61],
       [5.48],
       [6.34],
       [9.16],
       [7.36],
       [7.6 ],
       [5.

In [63]:
y_test

array([4.1 , 3.49, 2.08, 2.33, 1.94, 1.48, 1.86, 3.09, 4.21, 2.87, 3.65,
       4.  , 2.89, 2.6 , 2.99, 3.25, 1.86, 3.67, 2.37, 3.42, 2.48, 3.65,
       2.6 , 2.83, 4.08, 2.56, 3.58, 3.81, 4.09, 2.01, 3.63, 2.92, 3.51,
       1.94, 2.21, 3.34, 3.34, 3.23, 2.01, 2.61])

In [65]:
print(lr.predict(x_test[9]))

[2.92741425]
